name: Report code coverage

on:
  push:
    branches:
      - main
  pull_request:
    # Optionally configure to run only for changes in specific files. For example:
    paths:
      - contracts/**
      - test/**
      - foundry.toml
      - remappings.txt
      - .github/workflows/coverage-report.yml

jobs:
  coverage_report:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
          cache: "yarn"
          registry-url: https://npm.pkg.github.com/
          scope: "@chromatic-finance"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: yarn install
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # step generating a coverage report
      - name: Run coverage
        run: |
          forge coverage | sed -n -e '/| File/,$p' > coverage.ansi
          sed '1 i\## coverage report\n\n' coverage.ansi > coverage.md

      - name: Add coverage report to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact gas costs
          path: coverage.md
