# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish SDK

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: build SDK
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
          registry-url: https://npm.pkg.github.com/
          scope: "@usum-io"
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          yarn install
          yarn clean
          yarn build
      - name: publish
        working-directory: ./dist
        run: |
          npm version ${{ github.event.release.tag_name }}
          mv package.ver.json package.json
          npm publish
