# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish SDK

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: build SDK
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN}}
        run: |
          envsubst < .npmrc_ci > .npmrc
          yarn install
          yarn clean
          yarn build
          rm .npmrc
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      - name: publish
        env:
          SDK_VERSION: ${{ github.event.release.tag_name }}
        working-directory: ./dist
        run: |
          envsubst < package.json > package.ver.json
          mv package.ver.json package.json
          npm publish
