# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release and Publish SDK

on:
  pull_request:
    types:
      - closed
    paths:
      - contracts/**
      - deploy/**
      - package.sdk.json
      - hardhat.config.ts
      - .github/workflows/release-publish-sdk.yml
permissions:
  contents: write

jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semantic-release.outputs.tag }}
      # changelog: ${{ steps.semantic-release.outputs.changelog }}
    steps:
      - uses: chromatic-protocol/action-semantic-release@main
        id: semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  Publish:
    needs: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: chromatic-protocol/action-setup-foundry-yarn@v1
        with:
          scope: '@chromatic-protocol'
          ignore-scripts: false
          node-auth-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: build SDK
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        run: |
          yarn clean
          yarn build
      - name: publish
        working-directory: ./dist
        run: |
          npm version ${{ needs.Release.outputs.tag }}
          npm publish
      # export src.ts to chromatic-protocol/sdk-typechain
      - name: export src.ts
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_SDK_TYPECHAIN }}
          publish_dir: ./dist/src.ts
          external_repository: chromatic-protocol/sdk-typechain
          destination_dir: src.ts
          publish_branch: develop
