# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: release and publish sdk

on:
  pull_request:
    types:
      - closed
    paths:
      - contracts/**
      - deploy/**
      - package.json
      - hardhat.config.ts
      - .github/workflows/release-publish-sdk.yml
permissions:
  contents: write

jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
    steps:
      - uses: actions/checkout@v3 # Checkout our working repository
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: false
          pre-release: true
          git-push: true
          skip-on-empty: false
          # skip-version-file: false
          # skip-commit: false
      - name: Create Release # This action will create the actual release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: true
  Publish:
    needs: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: chromatic-protocol/action-setup-foundry-yarn@v1
        with:
          scope: '@chromatic-protocol'
          ignore-scripts: false
          node-auth-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: generate typechain code and publish contracts
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn clean
          yarn build
          yarn publish
      - uses: chromatic-protocol/action-github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_ACTION_APP_ID }}
          private_key: ${{ secrets.PR_ACTION_PRIVATE }}
      # make a PR to chromatic-protocol/sdk
      - uses: actions/checkout@v3
        with:
          repository: chromatic-protocol/sdk
          ref: main
          path: sdk
          token: ${{ steps.generate-token.outputs.token }}
      - run: |
          rm -rf sdk/src/gen/*
          cp -r package-build/src.ts/* sdk/src/gen/
      - name: pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: develop
          path: sdk
          add-paths: src/gen/**
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ github.event.pull_request.title }}
